blank_issues_enabled: false
contact_links:
  - name: Reportar vulnerabilidade de segurança
    url: mailto:romullodf@gmail.com
    about: Caso você identifique uma falha de segurança, entre em contato por e-mail. Não crie uma issue pública.
